In [15]:
#imports
#pip install numpy
import numpy as np
#pip install pandas
import pandas as pd
#pip install --upgrade tensorflow
import tensorflow as tf
from tensorflow import keras
#standard library
import os

In [16]:
#this function allows to read the csv files from the logs of the attentive cursor dataset
#path_logs : path to the logs of the dataset with the files containing the list of inputs for each user
#path_csv : path to the groundtruth.csv containing the attention score of the each user
#dfs : array containing, for each user, its attention score and the count of its inputs
def get_csv_data(path_logs, path_csv):
    data = pd.read_csv(path_csv, sep='\t')
    dfs = []
    for dirname, _, filenames in os.walk(path_logs):
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(dirname, filename).replace('\\', '/')
                df = pd.read_csv(file_path,sep=' ')
                
                row = data.loc[data['log_id'] == int(filename[:-4])] # https://stackoverflow.com/questions/17071871/how-do-i-select-rows-from-a-dataframe-based-on-column-values
                # print(row)
                arr = row.values.tolist()
                arr.append(df)
                dfs.append(arr)
    return dfs

In [17]:
#loading the data
dfs = get_csv_data('../the-attentive-cursor-dataset/logs', '../the-attentive-cursor-dataset/groundtruth.tsv')

In [18]:
#keeping the attention score and the amount of each input for each user
cleandf = []
for row in range(len(dfs)):
    cleandf.append([dfs[row][0][2],dfs[row][1]['event'].value_counts()])

In [19]:
#removing 'useless input types from the data'
tab = np.array(cleandf, dtype='object')
removed = ['mouseup','focus','load','beforeunload','unload','touchend'] #arbitrary list of input types to remove
for row in tab :
    for input in removed : 
        if input in row[1].keys() :
            row[1].pop(input)

#searching the data for every other input types
all_inputs = []
for row in tab :
    for input in row[1].keys() :
        if input not in all_inputs :
            all_inputs.append(input)
all_inputs.sort()
print(all_inputs)

['blur', 'click', 'contextmenu', 'copy', 'keydown', 'keyup', 'mousedown', 'mousemove', 'mouseover', 'resize', 'scroll', 'select', 'touchmove', 'touchstart']


In [20]:
#normaliations and the removal of extremes data are kept commented because they did not affect the accuracy
#of the model in any significant way but are kept in the code for future devs to know what has been tried on
#this model

#normalisation v1
"""
for input in all_inputs :
    tmp = []
    for row in tab :
        if input in row[1].keys() :
            tmp.append(row[1].get(input))
    mean = np.mean(tmp)
    for row in tab :
        if input in row[1].keys() :
            row[1][input] = row[1][input]/mean

print(tab)
"""
#normalisation v3
"""
for input in all_inputs :
    max = 0
    for row in tab :
        if input in row[1].keys() :
            if row[1].get(input) > max :
                max = row[1].get(input)
    for row in tab :
        if input in row[1].keys() :
            row[1][input] = row[1][input]/max
"""

'\nfor input in all_inputs :\n    max = 0\n    for row in tab :\n        if input in row[1].keys() :\n            if row[1].get(input) > max :\n                max = row[1].get(input)\n    for row in tab :\n        if input in row[1].keys() :\n            row[1][input] = row[1][input]/max\n'

In [21]:
tmp_all_x = [] #stock a python array version of the data shaped as the entry of the model
tmp_all_y = [] #stock a python array version of the data shaped as the results of the model (for training purpose)

for row in tab :
    tmp_all_x.append([])
    for input in all_inputs :
        if input in row[1].keys() :
            tmp_all_x[len(tmp_all_x)-1].append(row[1].get(input))
        else :
            tmp_all_x[len(tmp_all_x)-1].append(0)
    tmp_all_y.append(row[0])

all_x = np.array(tmp_all_x) #numpy array version of the shaped data
all_y = np.array(tmp_all_y)
print(all_x)

[[3 2 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [2 0 0 ... 0 0 0]
 ...
 [2 1 0 ... 0 0 0]
 [3 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]


In [22]:
#normalisation v2
"""
for i in range(len(all_inputs)) :
    print(i)
    tmp = []
    for row in all_x :
        tmp.append(row[i])
    mean = np.mean(tmp)
    for row in all_x :
        row[i] = row[i]/mean
    
print(all_x)
"""

#enlevage des données extrèmes (faire une normalisation avant)
"""
i = 0
bad_rows = []
for row in range(len(all_x)) :
    for element in all_x[row] :
        if element > 5 :
            i +=1
            bad_rows.append(row)
            continue

all_x = np.delete(all_x,bad_rows, axis=0)
print(all_x)
"""

'\ni = 0\nbad_rows = []\nfor row in range(len(all_x)) :\n    for element in all_x[row] :\n        if element > 5 :\n            i +=1\n            bad_rows.append(row)\n            continue\n\nall_x = np.delete(all_x,bad_rows, axis=0)\nprint(all_x)\n'

In [23]:

inputs = keras.Input(shape=(len(all_inputs),))
x = tf.keras.layers.Dense(1, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(6, activation=tf.nn.softmax)(x)

model = keras.Model(inputs=inputs, outputs = outputs)

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

#list of inputs (uncoment to see)
print('all used input types : ')
print(all_inputs)
#all_inputs correspond to all the inputs type minus
print('all removed inputs : ')
print(removed)

all used input types : 
['blur', 'click', 'contextmenu', 'copy', 'keydown', 'keyup', 'mousedown', 'mousemove', 'mouseover', 'resize', 'scroll', 'select', 'touchmove', 'touchstart']
all removed inputs : 
['mouseup', 'focus', 'load', 'beforeunload', 'unload', 'touchend']


In [24]:
print(all_x[1])

[0 1 0 0 0 0 1 9 3 0 7 0 0 0]


In [25]:
history = model.fit(all_x, all_y, epochs=20, validation_split=0.1)

Epoch 1/20
82/82 [==============================] - 1s 5ms/step - loss: 1.6894 - accuracy: 0.3373 - val_loss: 1.6564 - val_accuracy: 0.4261
Epoch 2/20
82/82 [==============================] - 0s 3ms/step - loss: 1.6708 - accuracy: 0.3697 - val_loss: 1.6397 - val_accuracy: 0.4261
Epoch 3/20
82/82 [==============================] - 0s 2ms/step - loss: 1.6626 - accuracy: 0.3697 - val_loss: 1.6325 - val_accuracy: 0.4261
Epoch 4/20
82/82 [==============================] - 0s 3ms/step - loss: 1.6579 - accuracy: 0.3697 - val_loss: 1.6295 - val_accuracy: 0.4261
Epoch 5/20
82/82 [==============================] - 0s 2ms/step - loss: 1.6548 - accuracy: 0.3697 - val_loss: 1.6287 - val_accuracy: 0.4261
Epoch 6/20
82/82 [==============================] - 0s 2ms/step - loss: 1.6530 - accuracy: 0.3697 - val_loss: 1.6254 - val_accuracy: 0.4261
Epoch 7/20
82/82 [==============================] - 0s 3ms/step - loss: 1.6516 - accuracy: 0.3697 - val_loss: 1.6265 - val_accuracy: 0.4261
Epoch 8/20
82/82 [==

In [26]:
import tensorflowjs as tfjs
tfjs.converters.save_keras_model(model, './model')

In [28]:
num_array = np.array([ 0, 17, 0, 0, 0, 0, 21, 324, 28, 0, 0, 0, 0, 0 ])
prediction = model.predict(num_array.reshape(1, -1))
print(prediction)

[[0.         0.         0.         0.         0.99735427 0.00264577]]
